# Generated by Django 4.1.3 on 2023-02-04 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Shopper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ad soyad')),
                ('phone', models.CharField(max_length=120, verbose_name='Telefon')),
                ('city', models.CharField(max_length=120, verbose_name='Şehir')),
                ('town', models.CharField(max_length=120, verbose_name='İlçe')),
                ('suburb', models.CharField(max_length=120, verbose_name='Mahalle')),
                ('street', models.CharField(max_length=120, verbose_name='Cadde')),
                ('homeno', models.CharField(max_length=120, verbose_name='Bina no')),
                ('homename', models.CharField(max_length=120, verbose_name='Bina Adı')),
                ('productdetail', models.CharField(max_length=255, verbose_name='Ürün detayı')),
                ('odemeturu', models.BooleanField(default=True, verbose_name='Nakit mi?')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Adı')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Fiyatı')),
                ('image', models.FileField(upload_to=None, verbose_name='Ürün Fotoğrafı')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(verbose_name='Satışta mı?')),
                ('offer', models.BooleanField(verbose_name='Kampanya var mı?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.category', verbose_name='Kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_now', models.DateField(auto_now_add=True, verbose_name='Sipariş Tarihi')),
                ('finished', models.BooleanField(default=False, verbose_name='Teslim Edildi')),
                ('productlist', models.ManyToManyField(to='Menu.product', verbose_name='Sipariş Listesi')),
                ('shopper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.shopper', verbose_name='Müşteri Bilgileri')),
            ],
        ),
    ]
