# Generated by Django 4.1.3 on 2023-02-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_product_desc_alter_product_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='productdetail',
            field=models.BooleanField(default=False, verbose_name='Acılı var mı ?'),
        ),
    ]
