# Generated by Django 4.1.3 on 2023-02-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_bill_productdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='productdetail',
        ),
        migrations.AlterField(
            model_name='shopper',
            name='productdetail',
            field=models.BooleanField(default=False, verbose_name='Acılı var mı ?'),
        ),
    ]
