# Generated by Django 4.1.3 on 2023-02-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0005_shopper_productaci_alter_shopper_productdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopper',
            name='productaci',
        ),
        migrations.AddField(
            model_name='product',
            name='productaci',
            field=models.BooleanField(default=False, verbose_name='Acılı var mı ?'),
        ),
    ]
