# Generated by Django 4.1.3 on 2023-02-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0006_remove_shopper_productaci_product_productaci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to='media/None', verbose_name='Ürün Fotoğrafı'),
        ),
    ]
