# Generated by Django 4.1.3 on 2023-02-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0011_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to='media', verbose_name='Ürün Fotoğrafı'),
        ),
    ]
