# Generated by Django 4.1.3 on 2023-02-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0012_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to='', verbose_name='Ürün Fotoğrafı'),
        ),
    ]
