# Generated by Django 4.1.3 on 2023-02-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0016_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productaci',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Acılı var mı ?'),
        ),
    ]
