# Generated by Django 4.1.3 on 2023-02-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0019_bill_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopper',
            name='date_now',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Sipariş Tarihi'),
        ),
        migrations.AddField(
            model_name='shopper',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Teslim Edildi'),
        ),
        migrations.AddField(
            model_name='shopper',
            name='productlist',
            field=models.ManyToManyField(to='Menu.product', verbose_name='Sipariş Listesi'),
        ),
        migrations.AddField(
            model_name='shopper',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Toplam Tutar'),
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
