# Generated by Django 4.1.3 on 2023-02-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0022_cari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cari',
            name='ciro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='ciro'),
        ),
        migrations.AlterField(
            model_name='cari',
            name='date_now',
            field=models.DateField(auto_now_add=True, db_index=True, null=True, verbose_name='Tarih'),
        ),
    ]
