# Generated by Django 4.1.3 on 2023-02-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0025_cari_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kebaplar', models.IntegerField(blank=True, default=0, null=True, verbose_name='Kebaplar')),
                ('pideler', models.IntegerField(blank=True, default=0, null=True, verbose_name='Pideler')),
                ('diger', models.IntegerField(blank=True, default=0, null=True, verbose_name='Diğer')),
            ],
        ),
    ]
