# Generated by Django 4.1.3 on 2023-02-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0026_daire'),
    ]

    operations = [
        migrations.AddField(
            model_name='daire',
            name='month',
            field=models.IntegerField(default=2, verbose_name='Ay'),
        ),
    ]
