# Generated by Django 4.1.3 on 2023-02-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0027_daire_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopper',
            name='alindi',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Sipariş alındı mesajı'),
        ),
        migrations.AddField(
            model_name='shopper',
            name='teslim',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Teslim edildi mesajı'),
        ),
    ]
